export const USERS = [
  {
    name: "Arvind",
    email: "tsarvind996@gmail.com",
    role: "Admin",
    status: "true",
    department: "Cardiology",
    last_logged: "24/03/2020",
  },
  {
    name: "Swetha",
    email: "swetz@gmail.com",
    role: "Normal",
    status: "false",
    department: "Oncology",
    last_logged: "12/03/2020",
  },
  {
    name: "Arjun",
    email: "arjunr@gmail.com",
    role: "Normal",
    status: "true",
    department: "Therapist",
    last_logged: "14/04/2019",
  },
  {
    name: "Divya",
    email: "divyas@gmail.com",
    role: "Normal",
    status: "true",
    department: "Nephrology",
    last_logged: "12/06/2020",
  },
  {
    name: "Max",
    email: "maxer@gmail.com",
    role: "Normal",
    status: "true",
    department: "Neurology",
    last_logged: "19/04/2018",
  },
  {
    name: "Akshaya",
    email: "akshay@gmail.com",
    role: "Normal",
    status: "true",
    department: "Cardiology",
    last_logged: "11/11/2019",
  },
  {
    name: "Paul",
    email: "pauler@gmail.com",
    role: "Admin",
    status: "true",
    department: "Therapist",
    last_logged: "18/09/2019",
  },
];
